import type { Metadata } from "next";
import { Hanken_Grotesk, Tomorrow } from "next/font/google";
import "./globals.css";

const serif = Tomorrow({
  weight: "400",
  subsets: ["latin"],
});

const sans = Hanken_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${serif.className} ${sans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
